#!/bin/sh

# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "$HOME/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.

which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi
ibus-daemon &
compton --backend glx --paint-on-overlay --vsync opengl-swc &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
# exec fluxbox -rc ~/.fluxbox/init-office
exec fluxbox -rc ~/.fluxbox/init-office &
fbpid=$!

sleep 1
{
   bluetoothd &
   command -v conky  && (sleep 1 && conky -c ~/.conky/celiora &)
   google-chrome --app=https://mail.google.com/mail/u/0/#inbox ~/.config/google-chrome/ &
   exec slack &
   feh --bg-scale ~/.wallpapers/waterfall.jpg && xrefresh
   command -v urxvtd && (urxvtd -q -f -o )
   command -v urxvtc && (urxvtc -name "main-term" )
   command -v urxvtc && (urxvtc -name "sec-term" )
   command -v urxvtc && (urxvtc -name "dev-term")
   xscreensaver -no-splash &
   exec ~/.dropbox-dist/dropboxd &
   exec /usr/lib/notification-daemon/notification-daemon &
   google-chrome &
   ginn-wrapper &
} &
 
wait $fbpid
# or if you want to keep a log:
# exec fluxbox -log "/home/jjalk/.fluxbox/log"
